#############################################################
# Folders opened with by file manager (yazi)
#############################################################

[[session]]
name = "Downloads folder"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "Dropbox folder"
path = "~/Dropbox"
startup_command = "y"

[[session]]
name = "Code folder"
path = "~/Dropbox/code folder"
startup_command = "y"

#############################################################
#  Folder or files open by $EDITOR (neovim)
#############################################################
[[session]]
name = "tmuxinator config"
path = "~/.config/tmuxinator"
startup_command = "nvim ."

[[session]]
name = "neovim config"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim ~/.config/sesh/sesh.toml"
