---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: system_distribution_config.stat.exists

- name: "ATUIN | Refresh {{ ansible_user_dir }}/.config/atuin folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/atuin"
    state: absent

# Link the Config File
- name: "ATUIN | Ensure atuin directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.config/atuin"

- name: "ATUIN | Copy atuin config"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/atuin"
    state: link
    force: yes

