---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: system_distribution_config
  no_log: true

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: system_distribution_config.stat.exists
  no_log: true

- name: "FASTFECTH | Refresh {{ ansible_user_dir }}/.config/fastfetch folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fastfetch"
    state: absent

- name: "FASTFETCH | Ensure fastfetch directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.config/fastfetch"

- name: "FASTFETCH | Create symbolic links for configuration files"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/fastfetch"
    state: link
    force: yes
